/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellSimularRouteImport } from './routes/_shell.simular'
import { Route as ShellPosCasamentoRouteImport } from './routes/_shell.pos-casamento'
import { Route as ShellPainelRouteImport } from './routes/_shell.painel'
import { Route as ShellMaisRouteImport } from './routes/_shell.mais'
import { Route as ShellConvidadosRouteImport } from './routes/_shell.convidados'
import { Route as ShellFornecedoresIndexRouteImport } from './routes/_shell.fornecedores.index'
import { Route as ShellFornecedoresIdRouteImport } from './routes/_shell.fornecedores.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSimularRoute = ShellSimularRouteImport.update({
  id: '/simular',
  path: '/simular',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPosCasamentoRoute = ShellPosCasamentoRouteImport.update({
  id: '/pos-casamento',
  path: '/pos-casamento',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPainelRoute = ShellPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMaisRoute = ShellMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConvidadosRoute = ShellConvidadosRouteImport.update({
  id: '/convidados',
  path: '/convidados',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFornecedoresIndexRoute = ShellFornecedoresIndexRouteImport.update({
  id: '/fornecedores/',
  path: '/fornecedores/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFornecedoresIdRoute = ShellFornecedoresIdRouteImport.update({
  id: '/fornecedores/$id',
  path: '/fornecedores/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/convidados': typeof ShellConvidadosRoute
  '/mais': typeof ShellMaisRoute
  '/painel': typeof ShellPainelRoute
  '/pos-casamento': typeof ShellPosCasamentoRoute
  '/simular': typeof ShellSimularRoute
  '/fornecedores/$id': typeof ShellFornecedoresIdRoute
  '/fornecedores/': typeof ShellFornecedoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/convidados': typeof ShellConvidadosRoute
  '/mais': typeof ShellMaisRoute
  '/painel': typeof ShellPainelRoute
  '/pos-casamento': typeof ShellPosCasamentoRoute
  '/simular': typeof ShellSimularRoute
  '/fornecedores/$id': typeof ShellFornecedoresIdRoute
  '/fornecedores': typeof ShellFornecedoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_shell/convidados': typeof ShellConvidadosRoute
  '/_shell/mais': typeof ShellMaisRoute
  '/_shell/painel': typeof ShellPainelRoute
  '/_shell/pos-casamento': typeof ShellPosCasamentoRoute
  '/_shell/simular': typeof ShellSimularRoute
  '/_shell/fornecedores/$id': typeof ShellFornecedoresIdRoute
  '/_shell/fornecedores/': typeof ShellFornecedoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/convidados'
    | '/mais'
    | '/painel'
    | '/pos-casamento'
    | '/simular'
    | '/fornecedores/$id'
    | '/fornecedores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/convidados'
    | '/mais'
    | '/painel'
    | '/pos-casamento'
    | '/simular'
    | '/fornecedores/$id'
    | '/fornecedores'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/onboarding'
    | '/_shell/convidados'
    | '/_shell/mais'
    | '/_shell/painel'
    | '/_shell/pos-casamento'
    | '/_shell/simular'
    | '/_shell/fornecedores/$id'
    | '/_shell/fornecedores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/simular': {
      id: '/_shell/simular'
      path: '/simular'
      fullPath: '/simular'
      preLoaderRoute: typeof ShellSimularRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pos-casamento': {
      id: '/_shell/pos-casamento'
      path: '/pos-casamento'
      fullPath: '/pos-casamento'
      preLoaderRoute: typeof ShellPosCasamentoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/painel': {
      id: '/_shell/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof ShellPainelRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mais': {
      id: '/_shell/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof ShellMaisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/convidados': {
      id: '/_shell/convidados'
      path: '/convidados'
      fullPath: '/convidados'
      preLoaderRoute: typeof ShellConvidadosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fornecedores/': {
      id: '/_shell/fornecedores/'
      path: '/fornecedores'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof ShellFornecedoresIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fornecedores/$id': {
      id: '/_shell/fornecedores/$id'
      path: '/fornecedores/$id'
      fullPath: '/fornecedores/$id'
      preLoaderRoute: typeof ShellFornecedoresIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellConvidadosRoute: typeof ShellConvidadosRoute
  ShellMaisRoute: typeof ShellMaisRoute
  ShellPainelRoute: typeof ShellPainelRoute
  ShellPosCasamentoRoute: typeof ShellPosCasamentoRoute
  ShellSimularRoute: typeof ShellSimularRoute
  ShellFornecedoresIdRoute: typeof ShellFornecedoresIdRoute
  ShellFornecedoresIndexRoute: typeof ShellFornecedoresIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellConvidadosRoute: ShellConvidadosRoute,
  ShellMaisRoute: ShellMaisRoute,
  ShellPainelRoute: ShellPainelRoute,
  ShellPosCasamentoRoute: ShellPosCasamentoRoute,
  ShellSimularRoute: ShellSimularRoute,
  ShellFornecedoresIdRoute: ShellFornecedoresIdRoute,
  ShellFornecedoresIndexRoute: ShellFornecedoresIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
